In [17]:
import pandas as pd
import numpy as np

In [18]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [19]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"

df = pd.read_csv(url)

df.head()

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa


In [20]:
X = df.drop('species', axis=1)

y = df['species']

In [21]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=2
)

## LOGISTIC REGRESSION

In [22]:
lr = LogisticRegression(max_iter=1000)

lr.fit(X_train, y_train)

pred = lr.predict(X_test)

print("Accuracy:", accuracy_score(y_test, pred))

Accuracy: 0.9666666666666667


## SVM

In [24]:
svm = SVC()

svm.fit(X_train, y_train)

pred2 = svm.predict(X_test)

print("Accuracy:", accuracy_score(y_test, pred2))

Accuracy: 0.9666666666666667


## DECISION TREE

In [27]:
tree = DecisionTreeClassifier()

tree.fit(X_train, y_train)

pred3 = tree.predict(X_test)

print("Accuracy:", accuracy_score(y_test, pred3))

Accuracy: 0.9333333333333333


## KNN

In [26]:
knn = KNeighborsClassifier()

knn.fit(X_train, y_train)

pred4 = knn.predict(X_test)

print("Accuracy:", accuracy_score(y_test, pred4))

Accuracy: 1.0


## CONFUSION MATRIX

In [28]:
cm = confusion_matrix(y_test, pred3)

print(cm)

[[14  0  0]
 [ 0  7  1]
 [ 0  1  7]]
